name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Verify current working directory
        run: pwd # Print the current directory to verify location

      - name: List directory contents
        run: ls -la # List the contents of the root directory

      - name: Verify if package.json exists
        run: ls -la ./frontend # Adjust to where package.json is located (frontend or root)

      - name: Install dependencies
        run: |
          cd ./frontend  # Change to the correct directory if needed (adjust if your package.json is in frontend)
          ls -la  # Verify the contents after changing directory
          npm install
        shell: bash

      - name: Build project
        run: |
          cd ./frontend  # Ensure you're in the correct directory before building
          npm run build
        shell: bash

      - name: List build directory contents
        run: |
          cd ./frontend/build  # Adjust this path to where your build output is generated
          ls -la  # Ensure the build directory exists and contains the correct files
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build # Adjust this to where your build output is located
