name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3 # Use the latest version

      # Step 2: List root directory contents
      - name: List root directory contents
        run: ls -la # Check if HTML files are in the correct location

      # Step 3: Check for index.html file
      - name: Check for index.html
        run: |
          if [ -f index.html ]; then
            echo "index.html found!"
          else
            echo "index.html NOT found!"
            exit 1  # Fail the job if index.html is missing
          fi

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Use the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Adjust this if your HTML files are in a different directory
          force_orphan: true # Create a new orphan branch for deployment
