name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Deploy on pushes to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3 # Use the latest version

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Ensure this is the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend # Adjust this if your HTML files are in a different directory
          force_orphan: false # No need to create a new branch, as it exists
